### ISSUE TITLE
have nested/commands and grouped commands ?

### ISSUE THREAD

**Issue by npf** [oar-team/kameleon#108]
e.g.
```
-step
  -microstep
    - rescue
      - exec_local ...
      - rescue
        - exec_local ...
        - exec_local ...
```
and
```
-step
  -microstep
    - rescue
      - exec_local ...
      - group
        - exec_local ...
        - exec_out ...
```

**Comment by mickours** [comment]
Kameleon do not provide advance features like this, and I think it shouldn't because we want to keep it simple. 

If you want if/then/else control flow just use bash scripts for that and not Kameleon syntax directly. 

Le 21 avril 2017 19:02:23 GMT+02:00, Pierre Neyron <notifications@github.com> a écrit :
>e.g.
>```
>-step
>  -microstep
>    - rescue
>      - exec_local ...
>      - rescue
>        - exec_local ...
>        - exec_local ...
>```
>and
>```
>-step
>  -microstep
>    - rescue
>      - exec_local ...
>      - group
>        - exec_local ...
>        - exec_out ...
>```
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/oar-team/kameleon/issues/108

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by npf** [comment]
nested already exist.

group is staight forward.
