### ISSUE TITLE
on_setup_clean steps are not executed in the right order

### ISSUE THREAD

**Issue by ArthurGarnier** [oar-team/kameleon#111]
Example : 

file_1.yaml sample : 
```
setup:
   -  setup_orchestrator
```

setup_orchestrator.yaml sample  : 
```
- on_setup_clean:
    - exec_in: command_1
```

file_2.yaml sample : 
```
extend file_1.yaml
setup:
   -  @base
   - my_step
```

my_step.yaml sample  : 
```
- on_setup_clean:
    - exec_in: command_2
```

In the clean section, command_2 is executed before command_1
If it's the expected behavior is there any way to bypass it in order to have command_1 before command_2 ?

**Comment by mickours** [comment]
Hi,
Yes, it is the expected behaviour, but this is missing in the documentation.

It works this way because most of the time the things you do in a steps must be cleaned after the the clean od the next steps i.e. if you do a chroot and then install some packages, you want the packages to be removed from the cache before you unmount your chroot.

@ArthurGarnier Did you find a way to make it works as you expected?

**Comment by mickours** [comment]
TODO: Explain this behaviour in the doc.

**Comment by ArthurGarnier** [comment]
@mickours Yes, I don't clean the packages used in command_1

**Comment by mickours** [comment]
TODO: Explain this behaviour in the doc: [here](http://kameleon.imag.fr/commands.html?highlight=hook#hooks)
