### ISSUE TITLE
Enable recursive use of kameleon variable (like in bash)

### ISSUE THREAD

**Issue by mickours** [oar-team/kameleon#53]
for example:
```
setup_packages: $$setup_packages git vim
```

**Comment by mickours** [comment]
Done in f906f26

**Comment by SalemHarrache** [comment]
Thanks !

**Comment by mickours** [comment]
Your welcome :)
I like to bump version 2.7.0 an to publish the documentation that I wrote but I cant find the way to do it...
Can you add to the readme how to do these two tasks?

**Comment by SalemHarrache** [comment]
It's not that complicated. You can use the script ``./scripts/bumpversion.py`` which will handle everything (incrementation, git tag creation, changelog update).

1) After each release, a new version has to be created (in this example, the 2.7.0 dev)
```
$ python2 ./scripts/bumpversion.py newversion minor  # 2.6.7 -> 2.7.0.dev
```

[work/commit]

2) Releasing a new version
```
$ python2 ./scripts/bumpversion.py release  # 2.7.0.dev -> 2.7.0 + git tag + changelog
$ gem build kameleon-builder.gemspec
$ gem push kameleon-builder-2.7.0.gem
```
You need a rubygem account and I have to give you permissions so that you can push

**Comment by npf** [comment]
@SalemHarrache can you write that in a RELEASING file in the root of kameleon sources, for instance ?
Thx
